--- 
- hosts: ecs
  remote_user: root
  tasks:
    - name: test shell
      shell: "echo test > /root/testshellfile"
      register: testvar
    - name: shell module return values
      debug:
        var: testvar