---

- name: install zabbix repo
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
    state: present

- name: install a list of package
  yum:
    name:
      - curl
      - gcc
      - openssl-devel
      - libnl3-devel
      - net-snmp-devel
      - python3
      - python3-devel
      - nginx
      - haproxy
      - keepalived
    state: present